export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_CATEGORY ='ADD_CATEGORY';
export const GET_CATEGORYLIST ='GET_CATEGORYLIST';
export const ADD_PLACE ='ADD_PLACE';
export const GET_PLACELIST='GET_PLACELIST';
export const GET_SERVICELISTS='GET_SERVICELISTS';
